### ISSUE TITLE
What about Retrofit?

### ISSUE THREAD

**Issue by dsrenesanse** [dfloureiro/News-API-Kotlin#1]
inside lib right? 
interface NewsAPI {
    @GET("{v2}/{top-headlines}")

    fun listNews(@Path("v2") version : String,
                 @Path("top-headlines") type : String,
                 @Query("country") country: String,
                 @Query("pageSize") pageSize: String,
                 @Query("category") category: String,
                 @Query("apiKey") key: String): Observable<ResponseBody>

    @GET("{v2}/{everything}")
    fun listSearchedNews(@Path("v2") version : String,
                 @Path("everything") type : String,
                 @Query("q") query: String,
                 @Query("language") language: String,
                 @Query("sortBy") sortBy: String,
                 @Query("pageSize") pageSize: String,
                 @Query("apiKey") key: String): Observable<ResponseBody>
}

**Comment by dfloureiro** [comment]
Hey, sorry for the long time. Yes, it uses Retrofit. The instance is provided by the injector:
https://github.com/dfloureiro/News-API-Kotlin/blob/master/newsapi/src/main/java/com/dfl/newsapi/di/Injector.kt
